### ISSUE TITLE
`mongo.BSON {a={1,2,3}}` segfaults

### ISSUE THREAD

**Issue by pbosetti** [neoxic/lua-mongo#7] opened 2018-07-25 14:51 UTC
The following

    mongo.BSON {a={__array, 1, 2, 3}}

segfaults, as well as the syntax in title. At least, an error, rather than a segfault, shall be issued by Lua.

**Comment by neoxic** [comment] 2018-07-25 20:06
Please see this issue #2 and report back. Thanks!

**Comment by neoxic** [comment] 2018-08-06 03:52
No further feedback received. Closing as a duplicate of #2 ...

**Closed as completed by neoxic** 2018-08-06 03:52 UTC
